- name: Create the ELB only listening over port 80
  ec2_elb_lb:
    name: "{{ ELBNAME }}"
    state: present
    region: eu-west-1
    zones:
      - eu-west-1a
      - eu-west-1b
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
  register: elb

- name: Create EC2 instances
  ec2:
    key_name: devops-keypair
    instance_type: t2.micro
    image: ami-089cc16f7f08c4457
    user_data: "{{ USERDATA }}"
    region: eu-west-1
    group_id:
      - sg-0f76bfe3897837cc0
    wait: yes
    instance_tags:
      Name: web_server
      application: "{{ application }}"
    exact_count: 2
    count_tag:
      application: "{{ application }}"
  register: ec2_instances

- name: Wait for servers to come online
  wait_for:
    host: "{{ item.public_ip }}"
    port: 80
    timeout: 180
  with_items: "{{ ec2_instances.tagged_instances }}"
  ignore_errors: True

- name: Add each EC2 instance to the ELB
  ec2_elb:
    state: present
    ec2_elbs: "{{ ELBNAME }}"
    region: "{{ item.region }}"
    instance_id: "{{ item.id }}"
  with_items: "{{ ec2_instances.tagged_instances }}"
